ShellCheck corrections

diff --git a/vpn_eth b/vpn_eth
--- a/vpn_eth
+++ b/vpn_eth
@@ -17,13 +17,18 @@ VERSION=1.3.0
 SETTINGS=~/.vpn_eth.rc
 VPZS_CACHE=~/.vpn_eth.vpzs
 REALMS_CACHE=~/.vpn_eth.realms
+XBAR=
 
 ################################################################################
 # Prints an error message and exits
 #  $1 error message
 error() {
-    echo "Error: $1" 1>&2
-    exit
+    if [ -z "${XBAR}" ] ; then
+        echo "Error: $1" 1>&2
+        exit
+    else
+        echo "Error"
+    fi
 }
 
 if [ -n "${SSH_CLIENT}" ]; then
@@ -222,9 +227,10 @@ check_required_prog "${VPN}"
 PWD=$(pwd)
 if [ "${PWD}" = "${HOME}/Library/Application Support/xbar/plugins" ]; then
 
+    XBAR=1
+    
     # menu item handlers
     if [ "$1" = "turn_vpn_off" ]; then
-        echo disconnect >> $d
         ${VPN} disconnect
     elif [ "$1" = "turn_vpn_on" ]; then
         
@@ -246,24 +252,27 @@ if [ "${PWD}" = "${HOME}/Library/Application Support/xbar/plugins" ]; then
     stats=$( "${VPN}" stats );
 
     # set isVpnOn (connected => true; disconnected => false)
-    if echo "$stats" | grep "Connection State" | grep -v Management | grep -q Connected; then
+    if echo "${stats}" | grep "Connection State" | grep -v Management | grep -q Connected; then
         isVpnOn=true;
     else
         isVpnOn=false;
     fi;
 
     # menu title
-    $isVpnOn && echo "🟢 VPN" || echo "⚪️ VPN";
+    ${isVpnOn} && echo "🟢 VPN" || echo "⚪️ VPN";
 
     # separator
     echo "---";
 
     # menu items
-    if $isVpnOn; then
-        echo "Connected to https://$SERVER/$VPZ";
-        echo "As $USER@$REALM.ethz.ch";
-        echo "Since $(echo "$stats" | grep Duration | awk '{print $2}' | sed 's/:..$//') (hh:mm)";
-        echo "$stats" | grep -E 'Client Address|Bytes (Sent|Received)|Prot|Cipher' | \
+    if ${isVpnOn}; then
+        echo "Connected to https://${SERVER}/${VPZ}";
+        echo "As ${USER}@${REALM}.ethz.ch";
+
+        since=$(echo "${stats}" | grep Duration | awk '{print $2}' | sed 's/:..$//')        
+        echo "Since ${since} (hh:mm)";
+        
+        echo "${stats}" | grep -E 'Client Address|Bytes (Sent|Received)|Prot|Cipher' | \
             sed 's/^ *//; s/:  */: /';
         echo "Disconnect now | bash='$0' param1=turn_vpn_off terminal=false";
         echo "Refresh statistics | refresh=true";
